version: 2
jobs:
  build-node10:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run ci

  build-node12:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run ci

  build-node14:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run ci

  master-check:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run lerna:nightly

  deploy:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run ci
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn run lerna:publish

workflows:
  version: 2
  commit:
    jobs:
      - build-node10
      - build-node12
      - build-node14
      - deploy:
          context: ui5-typescript
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
